Repository Master-delta-force/bikeapp, pull requests merged in 2020-06, with the labels that each got.

#72 DFBW-71 Created contribution guidelines in GitHub Project
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  package-lock.json
  package.json
Labels: documentation

#63 DFBW - 45 Create an input atom
  package-lock.json
  src/components/atoms/Input.svelte
Labels: Feature, Frontend

#64 DFBW - 46 Create a notification counter atom
  src/components/atoms/Notification.svelte
Labels: Feature, Frontend

#74 DFBB-73 Project not initializing on dev mode
  src/config/index.js
Labels: bug

#61 DFBW-52 Created a textarea atom
  src/components/atoms/Textarea.svelte
Labels: Feature, Frontend

#69 DFBW-50 Created a map atom
  src/components/atoms/Map.svelte
Labels: Feature, Frontend

#68 DFBB-67 Created a new API endpoints about brands and types of bikes
  api/bikes_types.js
  api/brands.js
  src/server.js
Labels: Backend, Feature

#76 DFBW-75 Server Crashed
  src/server.js
Labels: bug

#78 DFBB ADDED-77 middleware to validate a jwt token in the api endpoints
  .env.example
  package-lock.json
  package.json
  src/config/index.js
  src/middleware/auth/jwt.js
  src/server.js
  src/utils/strategy/jwt.js
Labels: Backend, Feature

#79 DFBW-3 Profile Component
  src/components/Nav.svelte
  src/components/atoms/Button.svelte
  src/components/atoms/Image.svelte
  src/components/atoms/Input.svelte
  src/routes/profile.svelte
Labels: Feature, Frontend
